server:
  port: 8080

spring:
  datasource:
    username: root
    password: zxy130904
    url: jdbc:mysql://localhost:3306/BookStore?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://zxy:123456@localhost:27017/bookstore?gssapiServiceName=mongodb
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.backend.bookstore.entity
